/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LaboratoryWork3;

import javax.swing.JOptionPane;

/**
 *
 * @author redenval
 */
public class Main extends javax.swing.JFrame {

    int MIN = 0;
    int MAX = 100;
    int M1P = 25; // 25%
    int M2P = 40; // 40%
    int TAP = 35; // 35%
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentName = new javax.swing.JTextField();
        studentNumber = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        milestone2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        milestone1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        terminalAssessment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        resMilestone1 = new javax.swing.JLabel();
        resMilestone2 = new javax.swing.JLabel();
        resTerminalAssessment = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        resTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 240, -1));
        getContentPane().add(studentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 240, -1));

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 690, 40));

        jLabel1.setText("Student Number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setText("Result");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));
        getContentPane().add(milestone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 190, -1));

        jLabel3.setText("Milestone 2 (100 Points):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        jLabel4.setText("Milestone 1 (100 Points):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));
        getContentPane().add(milestone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 190, -1));

        jLabel5.setText("Terminal Assessment (100 Points):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));
        getContentPane().add(terminalAssessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 120, -1));

        jLabel6.setText("Student Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel7.setText("Milestone 1 (25%):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 20));

        jLabel8.setText("Milestone 2 (40%):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 20));

        jLabel9.setText("Terminal Assessment (35%):");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, 20));

        resMilestone1.setText("0%");
        getContentPane().add(resMilestone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, 20));

        resMilestone2.setText("0%");
        getContentPane().add(resMilestone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 20));

        resTerminalAssessment.setText("0%");
        getContentPane().add(resTerminalAssessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 20));

        jLabel10.setText("Total (100%):");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 20));

        resTotal.setText("0%");
        getContentPane().add(resTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        String m1s = milestone1.getText();
        String m2s = milestone2.getText();
        String tas = terminalAssessment.getText();
        
        Boolean inputs = !m1s.isEmpty() && !m2s.isEmpty() && !tas.isEmpty();
        
        if(!inputs) {
            JOptionPane.showMessageDialog(null, "Please fill out missing fields!");
            return;
        }
        
        try {
            int m1 = Integer.parseInt(m1s);
            int m2 = Integer.parseInt(m2s);
            int ta = Integer.parseInt(tas);
            
            Boolean valid = m1 >= MIN && m1 <= MAX && m2 >= MIN && m2 <= MAX && ta >= MIN && ta <= MAX;
            
            if(valid) {
                double m1d = (m1 / 100.00) * M1P;
                double m2d = (m2 / 100.00) * M2P;
                double tad = (ta / 100.00) * TAP;
                
                // setting the result
                resMilestone1.setText(m1d + "%");
                resMilestone2.setText(m2d + "%");
                resTerminalAssessment.setText(tad + "%");
                resTotal.setText((m1d + m2d + tad) + "%");
            } else {
                JOptionPane.showMessageDialog(null, "Please input numbers between " + MIN + " and " + MAX + " only!");
            }
            
        } catch(NumberFormatException err) { 
            JOptionPane.showMessageDialog(null, "Input is not a number! Try again!");
            milestone1.setText("");
            milestone2.setText("");
            terminalAssessment.setText("");
        }
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField milestone1;
    private javax.swing.JTextField milestone2;
    private javax.swing.JLabel resMilestone1;
    private javax.swing.JLabel resMilestone2;
    private javax.swing.JLabel resTerminalAssessment;
    private javax.swing.JLabel resTotal;
    private javax.swing.JTextField studentName;
    private javax.swing.JTextField studentNumber;
    private javax.swing.JTextField terminalAssessment;
    // End of variables declaration//GEN-END:variables
}
